export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REDUCE_ITEM = "CART_REDUCE_ITEM";
export const CART_REMOVE_ALL_ITEMS = "CART_REMOVE_ALL_ITEMS";
export const CART_CHECKOUT = "CART_CHECKOUT";
